<?php
/**
 * Tests the driver class
 *
 * PHP Version 5
 *
 * <pre>
 * ComTimeclock is a Joomla application to keep track of employee time
 * Copyright (C) 2007 Hunt Utilities Group, LLC
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * </pre>
 *
 * @category   Test
 * @package    ComTimeclockTest
 * @subpackage Test
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2008 Hunt Utilities Group, LLC
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @version    SVN: $Id$
 * @link       https://dev.hugllc.com/index.php/Project:ComTimeclock:JoomlaUI
 */
/** Require the JoomlaMock stuff */
require_once dirname(__FILE__).'/../../JoomlaMock/joomla.php';
require_once dirname(__FILE__).'/../../JoomlaMock/testCases/JModelTest.php';
require_once dirname(__FILE__).'/../../../admin/models/customers.php';

/**
 * Test class for driver.
 * Generated by PHPUnit_Util_Skeleton on 2007-10-30 at 08:44:25.
 *
 * @category   Test
 * @package    ComTimeclockTest
 * @subpackage Test
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2008 Hunt Utilities Group, LLC
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link       https://dev.hugllc.com/index.php/Project:ComTimeclock:JoomlaUI
 */
class ComTimeclockAdminModelCustomersTest extends JModelTest
{
    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @return null
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->sqlFile = array(
            dirname(__FILE__)."/../../../admin/install/timeclock_projects.sql",
            dirname(__FILE__)."/../../../admin/install/timeclock_users.sql",
            dirname(__FILE__)."/../../../admin/install/timeclock_prefs.sql",
            dirname(__FILE__)."/../../../admin/install/timeclock_timesheet.sql",
            dirname(__FILE__)."/../../../admin/install/timeclock_customers.sql",
            dirname(__FILE__)."/users.sql",
        );
        $this->o = new TimeclockAdminModelCustomers();
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @return null
     *
     * @access protected
     */
    protected function tearDown()
    {
        parent::tearDown();
        unset($this->o);
    }

    /**
     * Data provider
     *
     * @return array
     */
    public static function dataGetDataCache()
    {
        return array(
        );
    }
    /**
     * Data provider
     *
     * @return array
     */
    public static function dataStore()
    {
        return array(
            array(
                array(
                    "company" => "a",
                    "name" => "b",
                    "address1" => "c",
                    "address2" => "d",
                    "city" => "e",
                    "state" => "f",
                    "zip" => "g",
                    "country" => "h",
                    "notes" => "i",
                    "published" => "j",
                    "checked_out" => 0,
                    "checked_out_time" => "0000-00-00 00:00:00",
                    "bill_pto" => 1,
                ),
                "post",
                array(
                    "id" => null,
                    "company" => "a",
                    "name" => "b",
                    "address1" => "c",
                    "address2" => "d",
                    "city" => "e",
                    "state" => "f",
                    "zip" => "g",
                    "country" => "h",
                    "notes" => "i",
                    "published" => "j",
                    "checked_out" => 0,
                    "checked_out_time" => "0000-00-00 00:00:00",
                    "created_by" => 62,
                    "bill_pto" => 1,
                ),
                "store",
            ),
        );
    }
    /**
     * Data provider
     *
     * @return array
     */
    public static function dataStoreRet()
    {
        return array(
            array(null, "store", 13, array("id" => 13)),
            array("bind", "store", false, array("id" => 13)),
            array("check", "store", false, array("id" => 13)),
            array("store", "store", false, array("id" => 13)),
        );
    }


}

?>
