CREATE TABLE IF NOT EXISTS `#__timeclock_timesheet` (
  `timesheet_id` int(11) NOT NULL AUTO_INCREMENT,
  `project_id` int(11) NOT NULL DEFAULT '0',
  `user_id` int(11) NOT NULL DEFAULT '0',
  `hours1` float NOT NULL DEFAULT '0',
  `hours2` float NOT NULL DEFAULT '0',
  `hours3` float NOT NULL DEFAULT '0',
  `hours4` float NOT NULL DEFAULT '0',
  `hours5` float NOT NULL DEFAULT '0',
  `hours6` float NOT NULL DEFAULT '0',
  `worked` date NOT NULL DEFAULT '0000-00-00',
  `created_by` int(11) NOT NULL DEFAULT '0',
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `notes` text NOT NULL,
  `checked_out` int(11) NOT NULL DEFAULT '0',
  `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`timesheet_id`),
  UNIQUE KEY `project_id` (`project_id`,`user_id`,`worked`)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
