CREATE TABLE IF NOT EXISTS `#__timeclock_timesheet` (
  `timesheet_id` int NOT NULL,
  `project_id` int NOT NULL DEFAULT '0',
  `user_id` int NOT NULL DEFAULT '0',
  `hours1` float NOT NULL DEFAULT '0',
  `hours2` float NOT NULL DEFAULT '0',
  `hours3` float NOT NULL DEFAULT '0',
  `hours4` float NOT NULL DEFAULT '0',
  `hours5` float NOT NULL DEFAULT '0',
  `hours6` float NOT NULL DEFAULT '0',
  `worked` date NOT NULL,
  `created_by` int NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime DEFAULT NULL,
  `notes` text NOT NULL,
  `checked_out` int DEFAULT NULL,
  `checked_out_time` datetime DEFAULT NULL,
  PRIMARY KEY (`timesheet_id`),
  UNIQUE KEY `project_id` (`project_id`,`user_id`,`worked`)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
