CREATE TABLE IF NOT EXISTS `#__timeclock_projects` (
  `project_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL DEFAULT '',
  `description` text NOT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` datetime NOT NULL,
  `manager_id` int(11) NOT NULL DEFAULT '0',
  `research` smallint(6) NOT NULL DEFAULT '0',
  `type` enum('PROJECT','CATEGORY','PTO','HOLIDAY','UNPAID') NOT NULL DEFAULT 'PROJECT',
  `parent_id` int(11) NOT NULL DEFAULT '0',
  `wcCode1` int(11) NOT NULL DEFAULT '8803',
  `wcCode2` int(11) NOT NULL DEFAULT '0',
  `wcCode3` int(11) NOT NULL DEFAULT '0',
  `wcCode4` int(11) NOT NULL DEFAULT '0',
  `wcCode5` int(11) NOT NULL DEFAULT '0',
  `wcCode6` int(11) NOT NULL DEFAULT '0',
  `customer_id` int(11) NOT NULL DEFAULT '0',
  `department_id` int(11) NOT NULL DEFAULT '0',
  `max_daily_hours` tinyint(4) NOT NULL DEFAULT '0',
  `max_yearly_hours` int(11) NOT NULL DEFAULT '0',
  `min_hour_increment` int(11) NOT NULL DEFAULT '0',
  `checked_out` int(11) NOT NULL,
  `checked_out_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `published` tinyint(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`project_id`),
  UNIQUE KEY `ProjectName` (`name`,`parent_id`),
  KEY `customer_id` (`customer_id`),
  KEY `department_id` (`department_id`),
  KEY `manager_id` (`manager_id`)
) DEFAULT CHARSET=utf8;

INSERT IGNORE INTO `#__timeclock_projects` (`project_id`, `name`, `description`, `created_by`, `created`, `manager_id`, `research`, `type`, `parent_id`, `wcCode1`, `wcCode2`, `wcCode3`, `wcCode4`, `wcCode5`, `wcCode6`, `customer_id`, `department_id`, `checked_out`, `checked_out_time`, `published`) VALUES('0', 'COM_TIMECLOCK_GENERAL', 'COM_TIMECLOCK_GENERAL_DESC', NULL, '0000-00-00 00:00:00', 0, 0, 'CATEGORY', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '0000-00-00 00:00:00', 1);
