CREATE TABLE IF NOT EXISTS `#__timeclock_customers` (
  `customer_id` int NOT NULL,
  `company` varchar(64) NOT NULL DEFAULT '',
  `name` varchar(64) NOT NULL DEFAULT '',
  `address1` varchar(64) NOT NULL DEFAULT '',
  `address2` varchar(64) NOT NULL DEFAULT '',
  `city` varchar(64) NOT NULL DEFAULT '',
  `state` varchar(64) NOT NULL DEFAULT '',
  `zip` varchar(10) NOT NULL DEFAULT '',
  `country` varchar(64) NOT NULL DEFAULT 'US',
  `notes` text NOT NULL,
  `checked_out` int DEFAULT NULL,
  `checked_out_time` datetime DEFAULT NULL,
  `published` smallint NOT NULL,
  `contact_id` int NOT NULL DEFAULT '0',
  `created_by` int NOT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `bill_pto` tinyint NOT NULL,
  PRIMARY KEY (`customer_id`),
  KEY `created_by` (`created_by`),
  KEY `contact_id` (`contact_id`),
  KEY `published` (`published`)
) DEFAULT CHARSET=utf8;
