CREATE TABLE IF NOT EXISTS `#__timeclock_customers` (
  `customer_id` int(11) NOT NULL AUTO_INCREMENT,
  `company` varchar(64) NOT NULL DEFAULT '',
  `name` varchar(64) NOT NULL DEFAULT '',
  `address1` varchar(64) NOT NULL DEFAULT '',
  `address2` varchar(64) NOT NULL DEFAULT '',
  `city` varchar(64) NOT NULL DEFAULT '',
  `state` varchar(64) NOT NULL DEFAULT '',
  `zip` varchar(10) NOT NULL DEFAULT '',
  `country` varchar(64) NOT NULL DEFAULT 'US',
  `notes` text NOT NULL,
  `checked_out` int(11) NOT NULL,
  `checked_out_time` datetime NOT NULL,
  `published` smallint(6) NOT NULL,
  `contact_id` int(11) NOT NULL,
  `created_by` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  `bill_pto` tinyint(4) NOT NULL,
  PRIMARY KEY (`customer_id`),
  KEY `created_by` (`created_by`),
  KEY `contact_id` (`contact_id`),
  KEY `published` (`published`)
) DEFAULT CHARSET=utf8;
